[project]
name = "BeginnerTools"
version = "1.0.0"
[project.authors]
name = "Ta Tan Dat"
email = "tatandat110105@gmail.com"
description: "A wrapper around some popular module to help new user access and use it faster"
readme: "README.md"
requires-python = ">=3.8"

[tool.black]
line-length = 137